import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/main";
import AuthProvider from "@/context/authContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}
      >
        <AuthProvider>
          <div className="h-[64px] w-full">
            <Navbar />
          </div>
          <div className="flex-1">
            {children}
          </div>
        </AuthProvider> 
      </body>
    </html>
  );
}
